Repository subodhsaraswat/wsp-design-system, pull requests merged in 2021-12, with the labels that each got.

#56 Navigation active state fix
  css/main.css
  css/main.css.map
  js/script.js
  scss/component/_side-navbar.scss
Labels: enhancement

#58 enhancements and about page added
  about.html
  css/main.css
  css/main.css.map
  js/page.js
  js/script.js
  scss/pages/_page.scss
Labels: New Component

#60 Carousal Design
  carousel.html
  css/main.css
  css/main.css.map
  images/.DS_Store
  images/slider/slide1.svg
  images/slider/slide2.svg
  images/slider/slide3.svg
  js/script.js
  scss/component/_carousel.scss
  scss/main.scss
Labels: New Component

#62 Colors utilities added
  colors.html
  css/main.css
  css/main.css.map
  js/page.js
  scss/pages/_page.scss
Labels: Utility

#63 clearfix, visibility and position utility added
  clearfix.html
  js/page.js
  position.html
  visibility.html
Labels: Utility

#64 align, text and border added
  borders.html
  css/main.css
  css/main.css.map
  js/page.js
  scss/css/navigation.css
  scss/css/navigation.css.map
  scss/pages/_page.scss
  scss/utilities/_borders.scss
  scss/utilities/_text.scss
  text.html
  vertical-align.html
Labels: Utility

#66 sizing and float utility added
  css/main.css
  css/main.css.map
  float.html
  scss/pages/_page.scss
  sizing.html
Labels: Utility

#67 Poonam work
  css/main.css
  css/main.css.map
  display.html
  images/slider/.DS_Store
  scss/utilities/_display.scss
  spacing.html
Labels: New Component

#68 Flex added
  css/main.css
  css/main.css.map
  flex.html
  js/page.js
  scss/utilities/_flex.scss
Labels: New Component
