Repository subodhsaraswat/wsp-design-system, pull requests merged in 2021-11, with the labels that each got.

#35 Modal Added
  avatar.html
  css/main.css
  css/main.css.map
  images/photo/team-1.jpeg
  images/photo/team-2.jpeg
  images/photo/team-3.jpeg
  images/photo/team-4.jpeg
  images/photo/team-5.jpeg
  input.html
  js/script.js
  modal.html
  scss/base/_variable.scss
  scss/component/_avatar.scss
  scss/component/_close.scss
  scss/component/_input-group.scss
  scss/component/_modal.scss
  scss/main.scss
  scss/mixins/_forms.scss
  scss/pages/_home.scss
  scss/pages/_page.scss
Labels: New Component

#38 Common Sidebar Create and update the copytoClipboard Style and function
  alert.html
  avatar.html
  badge.html
  button.html
  checkbox.html
  collapse.html
  css/main.css
  css/main.css.map
  drawer.html
  flag.html
  index.html
  input.html
  js/page.js
  js/script.js
  label.html
  list-group.html
  modal.html
  navbar.html
  rating.html
  scss/base/_variable.scss
  scss/component/_input-group.scss
  scss/pages/_page.scss
  section-message.html
  select.html
  skeleton.html
  switch.html
  tab.html
  table.html
Labels: enhancement

#41 tooltip added
  css/main.css
  css/main.css.map
  js/page.js
  scss/component/_tooltip.scss
  scss/main.scss
  scss/pages/_page.scss
  tooltip.html
Labels: New Component

#42 popover added
  css/main.css
  css/main.css.map
  js/page.js
  js/script.js
  popover.html
  scss/component/_popover.scss
  scss/component/_tooltip.scss
  scss/main.scss
Labels: enhancement, New Component

#43 Upload Page
  button.html
  css/main.css
  css/main.css.map
  js/script.js
  scss/component/_upload.scss
  scss/main.scss
  scss/pages/_page.scss
  upload.html
Labels: New Component

#44 Poonam work
  alert.html
  css/main.css
  css/main.css.map
  flag.html
  js/script.js
  label.html
  pagination.html
  scss/component/_close.scss
  scss/component/_label.scss
  scss/component/_pagination.scss
  scss/main.scss
Labels: New Component

#45 timeline added
  css/main.css
  css/main.css.map
  js/page.js
  scss/component/_side-navbar.scss
  scss/component/_timeline.scss
  scss/main.scss
  timeline.html
Labels: enhancement, New Component

#46 Stepper Added
  css/main.css
  css/main.css.map
  js/page.js
  js/script.js
  scss/component/_stepper.scss
  scss/main.scss
  stepper.html
Labels: New Component

#49 Range Slider
  css/main.css
  css/main.css.map
  js/script.js
  scss/component/_slider.scss
  scss/component/_stepper.scss
  scss/main.scss
  slider.html
Labels: New Component

#51 tree added
  css/main.css
  css/main.css.map
  js/page.js
  js/script.js
  scss/component/_tree.scss
  scss/main.scss
  tree.html
Labels: New Component

#52 Progress bar added
  css/main.css
  css/main.css.map
  js/page.js
  js/script.js
  progress.html
  scss/base/_variable.scss
  scss/component/_progress.scss
  scss/main.scss
Labels: enhancement, New Component

#55 navigation added
  css/main.css
  css/main.css.map
  flag.html
  js/page.js
  js/script.js
  navigation.html
  scss/base/_variable.scss
  scss/component/_card.scss
  scss/component/_flag.scss
  scss/component/_navigation.scss
  scss/component/_side-navbar.scss
  scss/component/_stepper.scss
  scss/css/navigation.css
  scss/css/navigation.css.map
  scss/main.scss
  scss/pages/_home.scss
Labels: New Component
